server:
  port: 7070

spring:
  application:
    name: olive-gateway-server  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: olive-auth-service
          uri: lb://olive-auth-server
          predicates:
            - Path=/api/olive/1.0/doLogin
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/olive/1.0/doLogin, /api/v1/olive-login

        - id: olive-foundation-service
          uri: lb://olive-foundation-server
          predicates:
            - Path=/api/olive/1.0/foundation/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/olive/1.0/foundation/(?<segment>/?.*), /$\{segment}
        
        - id: crestone
          uri: lb://crestone-server
          predicates:
            - Path=/api/olive/1.0/crestone/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/olive/1.0/crestone/(?<segment>/?.*), /$\{segment}    

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://localhost:7071/.well-known/jwks.json"
          
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
      
#logging:
#  level:
#    root: trace    

#spring:
#  cloud:
#    gateway:
#      httpclient:
#        wiretap: true
#      httpserver:
#        wiretap: true

logging:
  level:
    reactor:
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: DEBUG      
  file:
    name: ./logs/olive-gateway-server.log
    
